name: Notify Discord on Push

on:
  push:
    branches:
      - live
      - dev

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "**Tuxedo Trades Github Push** Commit by: ${{ github.actor }} in ${{ github.repository }}"}' \
          "${{ secrets.DISCORD_WEBHOOK }}"
