name: Notify Discord on Push

on:
  push:
    branches:
      - live
      - dev

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          USER_AVATAR_URL="https://avatars.githubusercontent.com/${{ github.actor }}"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [{
              "title": "${{ github.actor }} ${{ github.ref_name }} branch commit",
              "url": "${{ github.event.head_commit.url }}",
              "description": "${{ github.event.head_commit.message }}",
              "color": #506b90,
              "author": {
                "name": "${{ github.actor }}",
                "url": "https://github.com/${{ github.actor }}",
                "icon_url": "'${USER_AVATAR_URL}'"
              }
            }]
          }' \
          "${{ secrets.DISCORD_WEBHOOK }}"
