name: Notify Discord on Push

on:
  push:
    branches:
      - live
      - dev

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          USER_AVATAR_URL="https://avatars.githubusercontent.com/${{ github.actor }}"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [{
              "title": "${{ github.actor }} pushed to '${GITHUB_REF#refs/heads/}'",
              "description": "${{ github.event.head_commit.message || 'Merge' }}",
              "color": 5263888,
              "author": {
                "name": "${{ github.actor }}",
                "url": "https://github.com/${{ github.actor }}",
                "icon_url": "'"$USER_AVATAR_URL"'"
              }
            }]
          }' \
          "${{ secrets.DISCORD_WEBHOOK }}"
